version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${CP_TAG}
    hostname: zookeeper
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker1:
    image: confluentinc/cp-server:${CP_TAG}
    hostname: broker1
    container_name: broker1
    restart: always
    ports:
      - "9091:9091"
      - "29091:29091"
      - "29093:29093"
    volumes:
      - ./security1:/etc/kafka/secrets/
      - ./client1:/tmp/producer/
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SSL:SSL
      KAFKA_LISTENERS: PLAINTEXT://:29091,SSL://:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29091,SSL://broker1:29093
      # KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.server.keystore.jks
      # KAFKA_SSL_KEY_PASSWORD: confluent
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker_sslkey_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker_sslkey_creds
      KAFKA_SSL_CLIENT_AUTH: "required"
      # KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: 1
      CONFLUENT_CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_METRICS_ENABLE: 'false'
      KAFKA_CONFLUENT_REPORTERS_TELEMETRY_AUTO_ENABLE: 'false'
      KAFKA_CONFLUENT_BALANCER_ENABLE: 'false'

## Second Cluster below

  zookeeper2:
    image: confluentinc/cp-zookeeper:${CP_TAG}
    hostname: zookeeper2
    container_name: zookeeper2
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
  broker4:
    image: confluentinc/cp-server:${CP_TAG}
    hostname: broker2
    container_name: broker2
    restart: always
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper2:2182'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: BROKER://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: BROKER://broker2:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: 1
      CONFLUENT_CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 1
      KAFKA_CONFLUENT_METRICS_ENABLE: 'false'
      KAFKA_CONFLUENT_REPORTERS_TELEMETRY_AUTO_ENABLE: 'false'
      KAFKA_CONFLUENT_BALANCER_ENABLE: 'false'
