---
services:
  broker:
    container_name: broker
    depends_on:
      - zookeeper
    environment:
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:9092
      CONFLUENT_METRICS_REPORTER_TOPIC_CREATE: 'true'
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INT://broker:9092, PLAINTEXT_EXT://localhost:29092
      KAFKA_BROKER_ID: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INT
      KAFKA_JMX_PORT: 9992
      KAFKA_LISTENERS: PLAINTEXT_INT://broker:9092, PLAINTEXT_EXT://broker:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_EXT:PLAINTEXT,PLAINTEXT_INT:PLAINTEXT
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    hostname: broker
    image: confluentinc/cp-enterprise-kafka:6.1.0
    ports:
      - '9092:9092'
      - '29092:29092'
    restart: always

  connect1:
    container_name: connect1
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    environment:
      CLASSPATH: /usr/share/java/kafka-connect-replicator/replicator-rest-extension-6.1.0.jar:/usr/share/java/monitoring-interceptors/*
      CONNECT_BOOTSTRAP_SERVERS: broker:9092
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: All
      CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_BOOTSTRAP_SERVERS: broker:9092
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
      CONNECT_GROUP_ID: connect-cluster
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_PLUGIN_PATH: /usr/share/java
      CONNECT_PRODUCER_CLIENT_ID: connect-worker-producer
      CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_BOOTSTRAP_SERVERS: broker:9092
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
      CONNECT_REST_ADVERTISED_HOST_NAME: connect1
      CONNECT_REST_EXTENSION_CLASSES: io.confluent.connect.replicator.monitoring.ReplicatorMonitoringExtension
      CONNECT_REST_PORT: 8083
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_TOPIC_CREATION_ENABLE: 'false'
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 'false'
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    hostname: connect1
    image: confluentinc/cp-enterprise-replicator:6.1.0
    ports:
      - '8083:8083'
    restart: always
    
  connect2:
    container_name: connect2
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    environment:
      CLASSPATH: /usr/share/java/kafka-connect-replicator/replicator-rest-extension-6.1.0.jar:/usr/share/java/monitoring-interceptors/*
      CONNECT_BOOTSTRAP_SERVERS: broker:9092
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: All
      CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_BOOTSTRAP_SERVERS: broker:9092
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
      CONNECT_GROUP_ID: connect-cluster
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_PLUGIN_PATH: /usr/share/java
      CONNECT_PRODUCER_CLIENT_ID: connect-worker-producer
      CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_BOOTSTRAP_SERVERS: broker:9092
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
      CONNECT_REST_ADVERTISED_HOST_NAME: connect2
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_TOPIC_CREATION_ENABLE: 'false'
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 'false'
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    hostname: connect2
    image: confluentinc/cp-enterprise-replicator:6.1.0
    restart: always
  control-center:
    container_name: control-center
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - connect1
      - connect2
    environment:
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_BOOTSTRAP_SERVERS: broker:9092
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 1
      CONTROL_CENTER_CONNECT_CLUSTER: http://connect1:8083
      CONTROL_CENTER_ID: 10
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_KAFKA_BOOTSTRAP_SERVERS: broker:9092
      CONTROL_CENTER_KAFKA_MYCLUSTER_BOOTSTRAP_SERVERS: broker:9092
      CONTROL_CENTER_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 1
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONTROL_CENTER_UI_AUTOUPDATE_ENABLE: 'true'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
    hostname: control-center
    image: confluentinc/cp-enterprise-control-center:6.1.0
    ports:
      - '9021:9021'
    restart: always
  schema-registry:
    container_name: schema-registry
    depends_on:
      - broker
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    hostname: schema-registry
    image: confluentinc/cp-schema-registry:6.1.0
    ports:
      - '8081:8081'
    restart: always
  zookeeper:
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:6.1.0
    restart: always
version: '3.5'